Sergio: updated support for lacal group

diff --git a/trunk/gc3pie/gc3libs/etc/gnfs-cmd b/trunk/gc3pie/gc3libs/etc/gnfs-cmd
--- a/trunk/gc3pie/gc3libs/etc/gnfs-cmd
+++ b/trunk/gc3pie/gc3libs/etc/gnfs-cmd
@@ -1,11 +1,25 @@
 #!/bin/bash
 
+OUTFILES_LIST="output.list"
+
 echo Start
 
-# readig input parameters
+# add . as valid PATH 
+export PATH=.:$PATH
+
+touch $OUTFILE_LIST
+
+if [ $# -ne 4 ]; then
+    echo "Wrong number of input paramenters. Expected 4, got $#" 
+    echo "Usage: gnfs-cmd <first value for special q> <special q range [first,first+cnt-1]> <number of threads> <input_files archive>"
+    exit 1
+fi
+
+# read input parameters
 f=$1;
 c=$2;
-t=$3;
+# t=$3;
+t=$CRYPTO_SLOTS
 archive=$4;
 
 # open archive
@@ -18,20 +32,24 @@ else
     echo "[ ok ]"
 fi
 
-echo -n "Checking required commands... "
-if [ ! -e ./gnfs-lasieve6 ]; then
-    echo "[ failed on ./gnfs-lasieve6 ]"
-    exit 1
-fi
-
-if [ ! -e ./tdsievemt ]; then
-    echo "[ failed on ./tdsievemt ]"
-    exit 1
-fi
-echo "[ ok ]"
-
 chmod u+x gnfs-lasieve6
 chmod u+x tdsievemt
+
+LASVIEW6=`which gnfs-lasieve6`
+TDSVIEW=`which tdsievemt`
+GZIP=`which gzip`
+
+echo -n "Checking required commands... "
+if [ ! -e "$LASVIEW6" ] || [ ! -e "$TDSVIEW" ] || [ ! -e "$GZIP" ]; then
+    echo "[failed]"
+    echo "LASVIEW6: $LASVIEW6"
+    echo "TDSVIEW: $TDSVIEW"
+    echo "GZIP: $GZIP"
+    exit 1
+fi
+
+# chmod u+x $LASVIEW6 $TDSVIEW
+
 mkdir pprod
 
 let j=$f+$c;
@@ -52,52 +70,72 @@ if [ $f -ge 3000000000 ]; then name="M8o_3000"; fi
 if [ $f -ge 4200000000 ]; then name="M8o_4200"; fi
 
 echo "alg sieve for $name, A=$A, $c spq in $f-$j";
-./gnfs-lasieve6 -t $t -b $name -avvDoW0s -A $A -f $f -c $c
+$LASVIEW6 -t $t -b $name -avvDoW0s -A $A -f $f -c $c
 iname=$name.lasieve-0.$f-$j.ab
-cat $name.lasieve-0.$f-$j.ab.nb2? $name.lasieve-0.$f-$j.ab.nb3[0-4] > $iname
+cat $name.lasieve-0.$f-$j.ab.nb2? $name.lasieve-0.$f-$j.ab.nb3[0-5] > $iname
 
-echo "tdsieve 991";
-./tdsievemt -t $t -b M991 -vs -a 500000000,99 -i $iname
-gzip M991.tdsieve.$f-$j
-cat $name.lasieve-0.$f-$j.ab.nb35 >> $name.lasieve-0.$f-$j.ab
+# echo "tdsieve 991";
+# $TDSVIEW -t $t -b M991 -vs -a 500000000,99 -i $iname
+# $GZIP M991.tdsieve.$f-$j
+# cat $name.lasieve-0.$f-$j.ab.nb35 >> $name.lasieve-0.$f-$j.ab
 echo "tdsieve 1081";
-./tdsievemt -t $t -b M1081 -vs -a 500000000,103 -i $iname
-gzip M1081.tdsieve.$f-$j
-echo "tdsieve 1111";
-./tdsievemt -t $t -b M1111 -vs -a 500000000,103 -i $iname
-gzip M1111.tdsieve.$f-$j
-echo "tdsieve 1129";
-./tdsievemt -t $t -b M1129 -vs -a 500000000,103 -i $iname
-gzip M1129.tdsieve.$f-$j
-cat $name.lasieve-0.$f-$j.ab.nb36 >> $name.lasieve-0.$f-$j.ab
-echo "tdsieve 1151";
-./tdsievemt -t $t -b M1151 -vs -a 500000000,105 -i $iname
-gzip M1151.tdsieve.$f-$j
-echo "tdsieve 1153";
-./tdsievemt -t $t -b M1153 -vs -a 500000000,105 -i $iname
-gzip M1153.tdsieve.$f-$j
-echo "tdsieve 1159";
-./tdsievemt -t $t -b M1159 -vs -a 500000000,105 -i $iname
-gzip M1159.tdsieve.$f-$j
-cat $name.lasieve-0.$f-$j.ab.nb37 >> $name.lasieve-0.$f-$j.ab
-echo "tdsieve 1177";
-./tdsievemt -t $t -b M1177 -vs -a 2000000000,138 -i $iname
-gzip M1177.tdsieve.$f-$j
-echo "tdsieve 1193";
-./tdsievemt -t $t -b M1193 -vs -a 2000000000,141 -i $iname
-gzip M1193.tdsieve.$f-$j
-echo "tdsieve 1199";
-./tdsievemt -t $t -b M1199 -vs -a 2000000000,141 -i $iname
-gzip M1199.tdsieve.$f-$j
+$TDSVIEW -t $t -b M1081 -vs -a 500000000,103 -i $iname
+$GZIP M1081.tdsieve.$f-$j
+echo M1081.tdsieve.$f-$j.gz >> $OUTFILES_LIST
 
+echo "tdsieve 1111";
+$TDSVIEW -t $t -b M1111 -vs -a 500000000,103 -i $iname
+$GZIP M1111.tdsieve.$f-$j
+echo M1111.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+
+echo "tdsieve 1129";
+$TDSVIEW -t $t -b M1129 -vs -a 500000000,103 -i $iname
+$GZIP M1129.tdsieve.$f-$j
+cat $name.lasieve-0.$f-$j.ab.nb36 >> $name.lasieve-0.$f-$j.ab
+echo M1129.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+
+echo "tdsieve 1151";
+$TDSVIEW -t $t -b M1151 -vs -a 500000000,105 -i $iname
+$GZIP M1151.tdsieve.$f-$j
+echo M1151.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+
+echo "tdsieve 1153";
+$TDSVIEW -t $t -b M1153 -vs -a 500000000,105 -i $iname
+$GZIP M1153.tdsieve.$f-$j
+echo M1153.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+
+echo "tdsieve 1159";
+$TDSVIEW -t $t -b M1159 -vs -a 500000000,105 -i $iname
+$GZIP M1159.tdsieve.$f-$j
+cat $name.lasieve-0.$f-$j.ab.nb37 >> $name.lasieve-0.$f-$j.ab
+echo M1159.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+
+echo "tdsieve 1177";
+$TDSVIEW -t $t -b M1177 -vs -a 2000000000,138 -i $iname
+$GZIP M1177.tdsieve.$f-$j
+echo M1177.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+
+echo "tdsieve 1193";
+$TDSVIEW -t $t -b M1193 -vs -a 2000000000,141 -i $iname
+$GZIP M1193.tdsieve.$f-$j
+echo M1193.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+
+echo "tdsieve 1199";
+$TDSVIEW -t $t -b M1199 -vs -a 2000000000,141 -i $iname
+$GZIP M1199.tdsieve.$f-$j
+echo M1199.tdsieve.$f-$j.gz >> $OUTFILES_LIST
+# cleanup
 rm $iname
 rm $name.lasieve-0.$f-$j.ab.nb??
 rm -r pprod
 
-echo "Collecting results to output file... "
-for i in *.gz
-do
-	echo $i \"\" >> output.files
-done
+# additional cleanup
+ls * | grep -v gz$ | grep -v log$ | xargs --replace rm {}
+
+#echo "Collecting results to output file... "
+#for i in *.gz
+#do
+#    echo $i \"\" >> output.files
+#done
 
 echo Done
